// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef _GAGGIMATE_UI_H
#define _GAGGIMATE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////
#include "screens/ui_InitScreen.h"
#include "screens/ui_ProfileScreen.h"
#include "screens/ui_MenuScreen.h"
#include "screens/ui_BrewScreen.h"
#include "screens/ui_SteamScreen.h"
#include "screens/ui_WaterScreen.h"
#include "screens/ui_StandbyScreen.h"
#include "screens/ui_StatusScreen.h"
#include "screens/ui_GrindScreen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_logo_png);   // assets/logo.png
LV_IMG_DECLARE( ui_img_indicator_png);   // assets/indicator.png
LV_IMG_DECLARE( ui_img_untitled_png);   // assets/Untitled.png
LV_IMG_DECLARE( ui_img_489054950);   // assets/gauge-fill.png
LV_IMG_DECLARE( ui_img_295763949);   // assets/angle-up-40x40.png
LV_IMG_DECLARE( ui_img_1455708189);   // assets/pressure-filled.png
LV_IMG_DECLARE( ui_img_2044104741);   // assets/power-40x40.png
LV_IMG_DECLARE( ui_img_979979123);   // assets/mug-hot-alt-80x80.png
LV_IMG_DECLARE( ui_img_783005998);   // assets/wind-80x80.png
LV_IMG_DECLARE( ui_img_545340440);   // assets/raindrops-80x80.png
LV_IMG_DECLARE( ui_img_363557387);   // assets/coffee-bean-80x80.png
LV_IMG_DECLARE( ui_img_445946954);   // assets/play-40x40.png
LV_IMG_DECLARE( ui_img_360122106);   // assets/clock-40x40.png
LV_IMG_DECLARE( ui_img_1424216268);   // assets/equality-40x40.png
LV_IMG_DECLARE( ui_img_834125362);   // assets/minus-small-40x40.png
LV_IMG_DECLARE( ui_img_390988422);   // assets/plus-small-40x40.png
LV_IMG_DECLARE( ui_img_1951499226);   // assets/thermometer-half-40x40.png
LV_IMG_DECLARE( ui_img_364513079);   // assets/wifi-20x20.png
LV_IMG_DECLARE( ui_img_1091371356);   // assets/bluetooth-alt-20x20.png
LV_IMG_DECLARE( ui_img_1765671371);   // assets/refresh-20x20.png
LV_IMG_DECLARE( ui_img_1732953241);   // assets/tap-60x60.png
LV_IMG_DECLARE( ui_img_1456692430);   // assets/pause-40x40.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
