// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef UI_PROFILESCREEN_H
#define UI_PROFILESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif


// SCREEN: ui_ProfileScreen
extern void ui_ProfileScreen_screen_init(void);
extern void ui_ProfileScreen_screen_destroy(void);
extern void ui_event_ProfileScreen( lv_event_t * e);
extern lv_obj_t *ui_ProfileScreen;
extern lv_obj_t *ui_ProfileScreen_tempTarget;
extern lv_obj_t *ui_ProfileScreen_tempGauge;
extern lv_obj_t *ui_ProfileScreen_ImgButton1;
extern lv_obj_t *ui_ProfileScreen_contentPanel;
extern lv_obj_t *ui_ProfileScreen_mainLabel;
extern void ui_event_ProfileScreen_profileChoices( lv_event_t * e);
extern lv_obj_t *ui_ProfileScreen_profileChoices;
extern lv_obj_t *ui_ProfileScreen_tempText;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

