// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef UI_STEAMSCREEN_H
#define UI_STEAMSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif


// SCREEN: ui_SteamScreen
extern void ui_SteamScreen_screen_init(void);
extern void ui_SteamScreen_screen_destroy(void);
extern void ui_event_SteamScreen( lv_event_t * e);
extern lv_obj_t *ui_SteamScreen;
extern lv_obj_t *ui_SteamScreen_tempTarget;
extern lv_obj_t *ui_SteamScreen_tempGauge;
extern lv_obj_t *ui_SteamScreen_ImgButton6;
extern lv_obj_t *ui_SteamScreen_contentPanel5;
extern lv_obj_t *ui_SteamScreen_mainLabel5;
extern void ui_event_SteamScreen_goButton( lv_event_t * e);
extern lv_obj_t *ui_SteamScreen_goButton;
extern void ui_event_SteamScreen_downTempButton( lv_event_t * e);
extern lv_obj_t *ui_SteamScreen_downTempButton;
extern void ui_event_SteamScreen_upTempButton( lv_event_t * e);
extern lv_obj_t *ui_SteamScreen_upTempButton;
extern lv_obj_t *ui_SteamScreen_targetTemp;
extern lv_obj_t *ui_SteamScreen_Image9;
extern lv_obj_t *ui_SteamScreen_tempText;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

