// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef UI_STATUSSCREEN_H
#define UI_STATUSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif


// SCREEN: ui_StatusScreen
extern void ui_StatusScreen_screen_init(void);
extern void ui_StatusScreen_screen_destroy(void);
extern void ui_event_StatusScreen( lv_event_t * e);
extern lv_obj_t *ui_StatusScreen;
extern lv_obj_t *ui_StatusScreen_tempTarget;
extern lv_obj_t *ui_StatusScreen_tempGauge;
extern lv_obj_t *ui_StatusScreen_ImgButton3;
extern lv_obj_t *ui_StatusScreen_contentPanel2;
extern lv_obj_t *ui_StatusScreen_targetDuration;
extern lv_obj_t *ui_StatusScreen_targetTemp;
extern void ui_event_StatusScreen_pauseButton( lv_event_t * e);
extern lv_obj_t *ui_StatusScreen_pauseButton;
extern lv_obj_t *ui_StatusScreen_Image7;
extern lv_obj_t *ui_StatusScreen_Image8;
extern lv_obj_t *ui_StatusScreen_currentDuration;
extern lv_obj_t *ui_StatusScreen_stepLabel;
extern lv_obj_t *ui_StatusScreen_phaseLabel;
extern lv_obj_t *ui_StatusScreen_barContainer;
extern lv_obj_t *ui_StatusScreen_preinfusePumpBar;
extern lv_obj_t *ui_StatusScreen_preinfuseBloomBar;
extern lv_obj_t *ui_StatusScreen_brewBar;
extern lv_obj_t *ui_StatusScreen_labelContainer;
extern lv_obj_t *ui_StatusScreen_preinfusePumpLabel;
extern lv_obj_t *ui_StatusScreen_preinfuseBloomLabel;
extern lv_obj_t *ui_StatusScreen_brewLabel;
extern lv_obj_t *ui_StatusScreen_brewVolume;
extern lv_obj_t *ui_StatusScreen_tempText;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

