// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: GaggiMate

#ifndef UI_WATERSCREEN_H
#define UI_WATERSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif


// SCREEN: ui_WaterScreen
extern void ui_WaterScreen_screen_init(void);
extern void ui_WaterScreen_screen_destroy(void);
extern void ui_event_WaterScreen( lv_event_t * e);
extern lv_obj_t *ui_WaterScreen;
extern lv_obj_t *ui_WaterScreen_tempTarget;
extern lv_obj_t *ui_WaterScreen_tempGauge;
extern lv_obj_t *ui_WaterScreen_ImgButton7;
extern lv_obj_t *ui_WaterScreen_contentPanel6;
extern lv_obj_t *ui_WaterScreen_mainLabel6;
extern void ui_event_WaterScreen_goButton( lv_event_t * e);
extern lv_obj_t *ui_WaterScreen_goButton;
extern void ui_event_WaterScreen_downTempButton( lv_event_t * e);
extern lv_obj_t *ui_WaterScreen_downTempButton;
extern void ui_event_WaterScreen_upTempButton( lv_event_t * e);
extern lv_obj_t *ui_WaterScreen_upTempButton;
extern lv_obj_t *ui_WaterScreen_targetTemp;
extern lv_obj_t *ui_WaterScreen_Image10;
extern lv_obj_t *ui_WaterScreen_tempText;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

